# Generated by Django 4.1 on 2022-08-17 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_materials_remove_account_materials'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materials',
            old_name='materials',
            new_name='name',
        ),
    ]
