# Generated by Django 4.1 on 2022-08-19 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_rename_materials_materials_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='slug',
        ),
    ]
