# Generated by Django 4.1 on 2022-08-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0007_remove_district_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='slug',
            field=models.SlugField(default='frien', max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
