# Generated by Django 4.1 on 2022-08-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0008_district_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='slug',
            field=models.SlugField(default='frien', max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
